version: v2
name: PR Too Big
slug: pr-too-big
type: content
summary: Keep Pull Requests manageable so they are easier to review
description: |
  Keep Pull Requests small so they are easier to review
default_configuration:
  installation:
    org: false
parameters:
  - name: max_changed_files
    description: Maximum number of files that can be changed in a PR
  - name: max_additions
    description: Maximum number of additions in a PR
  - name: max_deletions
    description: Maximum number of deletions in a PR
subscribed_events:
  - pull_request.opened
  - pull_request.reopened
  - pull_request.synchronize
  - check_run.requested_action
  - check_run.rerequested
