name: PR Too Big
slug: pr-too-big
type: meta
summary: Keep Pull Requests manageable so they are easier to review
description: |
  ## Features
  * Decide what is too big to fail
parameters:
  - name: max_changed_files
    description: Maximum number of files that can be changed in a PR
    required: no
    sample_value: 20
  - name: max_additions
    description: Maximum number of additions in a PR
    required: no
    sample_value: 200
  - name: max_deletions
    description: Maximum number of deletions in a PR
    required: no
    sample_value: 200
subscribed_events:
  - pull_request.edited
  - pull_request.opened
  - pull_request.reopened
  - pull_request.synchronize
  - check_run.requested_action
  - check_run.rerequested
