task:
  name: PR Too Big
  slug: pr-too-big
  summary: Keep Pull Requests manageable so they are easier to review
  description: |
    ## Features
    * Decide what is too big to fail
  subscribed_events:
    - pull_request.edited
    - pull_request.opened
    - pull_request.reopened
